[project]
name = "youtube-search-mcp"
version = "0.1.0"
description = "A local MCP server implementation that allows Claude Desktop to search for youtube videos."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.13.1",
    "youtube-search>=2.1.2",
]
